spring:
  application:
    name: phishing-filter
  datasource:
    url: jdbc:postgresql://localhost:5432/phishing-filter-db
    username: myuser
    password: mypass
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/master.xml
    parameters:
      event_log_retention_days: 30
    contexts: dev
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: phishing-group
      auto-offset-reset: earliest
  cassandra:
    keyspace-name: phishing_cache
    contact-points: localhost
    port: 9042
    local-datacenter: datacenter1
    schema-action: CREATE_IF_NOT_EXISTS

kafka:
  topic:
    phishing-message-log:
      name: "phishing-message"
      partitions: 3
      replication-factor: 1

cassandra:
  phishing-cache:
    ttl-days: 30

google:
  api-key: 1234

web-risk:
  confidence-threshold: SAFE